### ISSUE TITLE
onOptionRemove needs to conitnue execution after running custom hook

### ISSUE THREAD

**Issue by jhu-axanexa** [mondaycom/monday-ui-react-core#1236] opened 2023-04-27 18:51 UTC
https://github.com/mondaycom/monday-ui-react-core/blob/775073b11a69f1d3813f385defb67c6e60d5dd21/src/components/Dropdown/Dropdown.jsx#L195

this is returning and stopping execution; by doing this the internal selectedOption array doesnt' get updated and the UI doesn't get refreshed to reflect a removed option.  if you look at the onCustomChange, it follows the same design language but it doesn't do a return, it runs it and continues to run the internal logic as well

**Comment by SergeyRoyt** [comment] 2023-10-08 13:34
Seems like it was resolved by this PR https://github.com/mondaycom/monday-ui-react-core/pull/1244 - couldn't reproduce it anymore
Closing the issue
Thanks for reporting it, @jhu-axanexa !

**Closed by SergeyRoyt** 2023-10-08 13:34 UTC
